{% set name = "isofit" %}
{% set version = "2.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/isofit/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 77760f6f88229f8102dfb820efde51d617ee15a28a2cb75843596faa9a495a02 

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - setuptools
    - numpy >=1.11,<1.19.0
    - scipy >=1.3.0
    - matplotlib >=2.2.2
    - scikit-learn >=0.19.1
    - scikit-image >=0.16.2
    - spectral >=0.19
    - pytest >=3.5.1
    - pep8 >=1.7.1
    - python-xxhash >=1.2.0
    - pyyaml >=5.3.1
    - ray >= 0.8.5

test:
  imports:
    - {{ name }}

about:
  home: https://github.com/{{ name }}/{{ name }}
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Imaging Spectrometer Optimal FITting (ISOFIT)'
  description: |
    ISOFIT provides routines and utilities for fitting surface, atmosphere
    and instrument models to imaging spectrometer data
  dev_url: https://github.com/{{ name }}/{{ name }}
  doc_url: https://github.com/{{ name }}/{{ name }}/wiki
  doc_source_url: https://github.com/{{ name }}/{{ name }}/tree/master/docs

extra:
  recipe-maintainers:
    - pgbrodrick
    - winstonolson
    - davidraythompson
